services:
  congame:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "5100:5100"
    environment:
      CONGAME_WEB_DEBUG: "x"
      CONGAME_WEB_HTTP_HOST: "0.0.0.0"
      CONGAME_WEB_HTTP_PORT: "5100"
      CONGAME_WEB_URL_HOST: "127.0.0.1"
      CONGAME_WEB_URL_PORT: "5100"
      CONGAME_WEB_LOG_LEVEL: "debug"
      CONGAME_WEB_PROFILE: "x"
      DATABASE_URL: "postgres://congame:congame@postgres/congame"
    links:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: congame
      POSTGRES_USER: congame
      POSTGRES_PASSWORD: congame
    volumes:
      - "pg:/var/lib/postgresql/data"

volumes:
  pg:
