FROM congame-source:latest AS build

WORKDIR /src/congame
RUN raco exe -o smtp-proxy congame-smtp-proxy/main.rkt
RUN raco dist dist smtp-proxy


FROM ghcr.io/marckaufmann/congame-deploy:latest AS deploy

COPY --from=build /src/congame/dist /opt/congame
ENTRYPOINT ["dumb-init", "/opt/congame/bin/smtp-proxy"]
