FROM ghcr.io/marckaufmann/racket:7.9-cs-full

RUN apt-get update \
  && apt-get install -y --no-install-recommends firefox

WORKDIR /opt/congame
COPY .git /opt/congame/.git
COPY ci /opt/congame/ci
COPY congame /opt/congame/congame
COPY congame-core /opt/congame/congame-core
COPY study-tools /opt/congame/study-tools
COPY congame-example-study /opt/congame/congame-example-study
COPY congame-pjb-studies/ /opt/congame/congame-pjb-studies
COPY congame-price-lists/ /opt/congame/congame-price-lists
COPY congame-tests /opt/congame/congame-tests
COPY migrations /opt/congame/migrations
COPY resources /opt/congame/resources
COPY static /opt/congame/static

RUN ci/setup-catalogs.sh
RUN raco pkg install -D --auto --batch \
  congame-core/ \
  study-tools/ \
  congame-example-study/ \
  congame-pjb-studies/ \
  congame-price-lists/ \
  congame/ \
  congame-tests/
CMD ["raco", "test", "/opt/congame/congame-tests"]
