FROM ghcr.io/marckaufmann/racket:7.9-cs-full

WORKDIR /opt/congame
COPY .git /opt/congame/.git
COPY ci /opt/congame/ci
COPY congame /opt/congame/congame
COPY congame-core /opt/congame/congame-core
COPY congame-example-study /opt/congame/congame-example-study
COPY congame-tests /opt/congame/congame-tests
COPY migrations /opt/congame/migrations
COPY resources /opt/congame/resources
COPY static /opt/congame/static

RUN ci/setup-catalogs.sh
RUN raco pkg install -D --auto --batch congame-core/ congame-example-study/ congame/ congame-tests/
CMD ["raco", "test", "/opt/congame/congame-tests"]
