FROM ghcr.io/marckaufmann/congame-deploy:latest

COPY build/identity /opt/congame
COPY bin/run-congame-identity.sh /opt/congame/bin/run-congame-identity.sh
CMD ["dumb-init", "/opt/congame/bin/run-congame-identity.sh"]
