name: CI/CD
on: [push, pull_request]
jobs:
  run:
    name: "CI/CD"
    runs-on: "ubuntu-latest"

    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: congame
          POSTGRES_PASSWORD: congame
          POSTGRES_DB: congame
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Node packages
      run: npm install

    - name: Build Node assets
      run: npm run build

    - name: Log into GHCR
      run: |
        echo "$PAT" | docker login ghcr.io -u MarcKaufmann --password-stdin

    - name: Build base docker image
      run: |
        docker build -t "ghcr.io/marckaufmann/congame-base:latest" -f Dockerfile-base .
        docker tag "ghcr.io/marckaufmann/congame-base:latest" "congame-base:latest"

    - name: Build docker image
      run: |
        docker build -t "ghcr.io/marckaufmann/congame:$GITHUB_SHA" .
        docker tag "ghcr.io/marckaufmann/congame:$GITHUB_SHA" "congame:latest"

    - name: Test the application
      run: |
        docker build -t congame-tests:latest -f Dockerfile-tests .
        docker run --network=host --rm congame-tests raco north migrate -fu "postgres://congame:congame@127.0.0.1:${{ job.services.postgres.ports[5432] }}/congame"
        docker run \
          --network=host \
          -e CONGAME_TEST_DB_HOST \
          -e CONGAME_TEST_DB_PORT \
          -e CONGAME_TEST_DB_NAME \
          -e CONGAME_TEST_DB_USERNAME \
          -e CONGAME_TEST_DB_PASSWORD \
          --rm \
          congame-tests
      env:
        CONGAME_TEST_DB_HOST: 127.0.0.1
        CONGAME_TEST_DB_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
        CONGAME_TEST_DB_NAME: congame
        CONGAME_TEST_DB_USERNAME: congame
        CONGAME_TEST_DB_PASSWORD: congame

    - name: Push docker image
      run: docker push "ghcr.io/marckaufmann/congame:$GITHUB_SHA"
      env:
        PAT: ${{ secrets.PAT }}

    - name: Deploy staging
      run: ./ci/deploy.sh STAGING
      env:
        PAT: ${{ secrets.PAT }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}

    - name: Deploy production
      run: ./ci/deploy.sh PRODUCTION
      env:
        PAT: ${{ secrets.PAT }}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      if: >-
        startsWith(github.ref, 'refs/tags/v')
